import { useState } from 'react'
import { readLocalFile } from '../utils/localProject'
import './ActionPanel.css'

export default function ActionPanel({ projectName, files, stats, frameworks }) {
  const [activeSection, setActiveSection] = useState('stats')
  const [toast, setToast] = useState('')
  const [compileMode, setCompileMode] = useState('single')
  const [doc, setDoc] = useState('')
  const [prompt, setPrompt] = useState('')
  const [security, setSecurity] = useState(null)
  const [chunks, setChunks] = useState(null)
  const [maxTokens, setMaxTokens] = useState(4000)
  const [busy, setBusy] = useState(false)

  const say = msg => { setToast(msg); setTimeout(() => setToast(''), 2500) }
  const download = (name, text) => { const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'})); a.download=name; a.click(); setTimeout(()=>URL.revokeObjectURL(a.href),1000) }
  const readAll = async () => { const out=[]; for (const file of (files||[])) { try { out.push({file,content:await readLocalFile(file)}) } catch {} } return out }
  const ensure = () => { if (!files?.length) { say('⚠ Open a local folder first'); return false } return true }

  const compile = async () => { if(!ensure()) return; setBusy(true); try { const all=await readAll(); let text=''; for(const x of all) text += '/* --- '+x.file.path+' --- */\n'+x.content+'\n\n'; download((projectName||'project')+'_compiled.txt',text); say('✅ Compilation downloaded') } finally { setBusy(false) } }
  const makePrompt = async () => { if(!ensure()) return; const all=await readAll(); setPrompt('Analyze project '+projectName+' for architecture, dependencies, code quality, security risks, missing functionality and practical improvements.\n\nFiles:\n'+all.map(x=>x.file.path).join('\n')); setActiveSection('ai') }
  const makeDocs = async () => { if(!ensure()) return; const by={}; (files||[]).forEach(f=>by[f.language]=(by[f.language]||0)+1); setDoc('# '+(projectName||'Project')+'\n\n## Summary\n\n- Files: '+files.length+'\n- Folders: '+(stats?.total_folders||0)+'\n- Size: '+(stats?.total_size_str||'0B')+'\n- Frameworks: '+((frameworks||[]).join(', ')||'None detected')+'\n\n## Languages\n\n'+Object.entries(by).map(x=>'- '+x[0]+': '+x[1]+' files').join('\n')+'\n\n## Files\n\n'+files.map(f=>'- `'+f.path+'` ('+f.size_str+')').join('\n')); setActiveSection('docs') }
  const scanSecurity = async () => { if(!ensure()) return; setBusy(true); try { const patterns=[['Private Key',/BEGIN .*PRIVATE KEY/i,'high'],['API Key',/(api[_-]?key|apikey)\s*[:=]\s*["'][^"']{16,}/i,'high'],['Password',/(password|passwd)\s*[:=]\s*["'][^"']{6,}/i,'medium'],['Token',/(secret|token)\s*[:=]\s*["'][A-Za-z0-9_-]{16,}/i,'medium']]; const findings=[]; for(const f of files){ let c; try{c=await readLocalFile(f)}catch{continue}; c.split(/\r?\n/).forEach((line,i)=>{for(const p of patterns){if(p[1].test(line)){findings.push({type:p[0],severity:p[2],file:f.path,line:i+1,snippet:line.trim().slice(0,180)});break}}}) } setSecurity({risk_level:findings.some(x=>x.severity==='high')?'high':findings.length?'medium':'low',files_scanned:files.length,findings}); setActiveSection('security') } finally {setBusy(false)} }
  const makeChunks = async () => { if(!ensure()) return; setBusy(true); try { const all=await readAll(); const size=Math.max(500,maxTokens)*4; const out=[]; for(const x of all){for(let i=0,o=0;o<x.content.length;o+=size,i++) out.push({index:out.length+1,name:x.file.path+'#'+(i+1),estimated_tokens:Math.ceil(x.content.slice(o,o+size).length/4)})} setChunks({total_chunks:out.length,chunks:out}); setActiveSection('chunks') } finally {setBusy(false)} }

  return <div className="action-panel">
    {toast && <div className="ap-toast">{toast}</div>}
    <div className="ap-section-tabs">{['stats','compile','ai','docs','security','chunks'].map(s=><button key={s} className={'apt-btn '+(activeSection===s?'active':'')} onClick={()=>setActiveSection(s)}>{s==='stats'?'📊':s==='compile'?'⚡':s==='ai'?'✦':s==='docs'?'📝':s==='security'?'🛡':'🤖'}</button>)}</div>
    <div className="ap-body scrollable">
      {activeSection==='stats' && <div className="ap-content"><div className="ap-label">Local Project Stats</div>{stats ? <><div className="stat-grid"><div className="stat-card"><div className="sc-val">{stats.total_files}</div><div className="sc-lbl">files</div></div><div className="stat-card"><div className="sc-val">{stats.total_folders}</div><div className="sc-lbl">folders</div></div><div className="stat-card"><div className="sc-val">{stats.total_size_str}</div><div className="sc-lbl">total size</div></div><div className="stat-card"><div className="sc-val">{Object.keys(stats.language_breakdown||{}).length}</div><div className="sc-lbl">languages</div></div></div><div className="ap-label" style={{marginTop:12}}>Detected</div><div className="fw-tags">{(frameworks||[]).map(f=><span key={f} className="fw-tag">{f}</span>)}</div></> : <div className="ap-empty">Open a local folder to analyze it</div>}</div>}
      {activeSection==='compile' && <div className="ap-content"><div className="ap-label">Local Compilation</div><div className="mode-grid"><div className={'mode-card '+(compileMode==='single'?'active':'')} onClick={()=>setCompileMode('single')}><div className="mc-title">Single File</div><div className="mc-sub">→ combined .txt</div></div><div className="mode-card"><div className="mc-title">Local</div><div className="mc-sub">No server required</div></div></div><button className="btn primary full" onClick={compile} disabled={busy}>{busy?'⏳ Compiling...':'⚡ Compile & Download'}</button></div>}
      {activeSection==='ai' && <div className="ap-content"><div className="ap-label">AI Analysis Prompt</div>{!prompt?<button className="btn primary full" onClick={makePrompt}>✦ Generate AI Prompt</button>:<><div className="prompt-box">{prompt}</div><button className="btn full" onClick={()=>navigator.clipboard?.writeText(prompt)}>📋 Copy</button></>}</div>}
      {activeSection==='docs' && <div className="ap-content"><div className="ap-label">Project Documentation</div>{!doc?<button className="btn primary full" onClick={makeDocs}>📝 Generate PROJECT_SUMMARY.md</button>:<><div className="prompt-box mono">{doc}</div><button className="btn success full" onClick={()=>download('PROJECT_SUMMARY.md',doc)}>💾 Download .md</button></>}</div>}
      {activeSection==='security' && <div className="ap-content"><div className="ap-label">Local Security Scanner</div>{!security?<button className="btn orange full" onClick={scanSecurity} disabled={busy}>{busy?'⏳ Scanning...':'🛡 Run Security Scan'}</button>:<><div className={'risk-badge '+security.risk_level}>{security.risk_level==='low'?'✅ Low Risk':security.risk_level==='medium'?'⚠ Medium Risk':'🔴 High Risk'}<span className="risk-sub"> · {security.files_scanned} files</span></div>{security.findings.length===0?<div className="sec-clean">No matching secrets detected</div>:<div className="findings-list">{security.findings.map((f,i)=><div key={i} className={'finding '+f.severity}><div className="finding-header"><span className="finding-type">{f.type}</span><span className={'sev-badge '+f.severity}>{f.severity}</span></div><div className="finding-loc">{f.file}:{f.line}</div><div className="finding-snippet">{f.snippet}</div></div>)}</div>}</>}</div>}
      {activeSection==='chunks' && <div className="ap-content"><div className="ap-label">Local AI Code Chunking</div><div className="chunk-setting"><label>Max tokens</label><input type="number" value={maxTokens} onChange={e=>setMaxTokens(Number(e.target.value))} min={500} max={32000} step={500}/></div><button className="btn primary full" onClick={makeChunks} disabled={busy}>🤖 Generate Chunks</button>{chunks&&<div className="chunks-summary">{chunks.total_chunks} chunks generated</div>}</div>}
    </div>
  </div>
}